- name: Combine package lists
  set_fact:
    apt_install__packages: "{{ xfce_desktop_package_list_xfce + xfce_desktop_package_list }}"

- name: Configure APT
  ansible.builtin.include_role:
    name: debops.debops.apt

- name: Install XFCE Packages
  ansible.builtin.include_role:
    name: debops.debops.apt_install

- name: Install nodejs Packages
  ansible.builtin.include_role:
    name: debops.debops.nodejs

# TODO: remove package_list_host_snap from host_vars
- name: Install Snap packages
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | default(false) }}"
  loop: "{{ xfce_desktop_package_list_snap }}"

- name: Configure Systemd
  ansible.builtin.include_role:
    name: debops.debops.systemd

- name: Ensure correct permissions for snakeoil SSL key
  ansible.builtin.file:
    path: /etc/ssl/private/ssl-cert-snakeoil.key
    owner: root
    group: ssl-cert
    mode: '0640'
  notify: Restart xrdp

- name: Add xrdp user to ssl-cert group
  ansible.builtin.user:
    name: xrdp
    groups: ssl-cert
    append: yes
  notify: Restart xrdp
